name: ig_navigation
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytorch=1.11.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
    - ray[rllib,defaults]
    - igibson
    - bddl
    - hydra-core
    - tensorboard
