# Whatever is in this file will override the experiment
defaults:
  - experiment/search.yaml
  - _self_

# Where to save results by default
experiment_save_path: ray_results

# Training params
training_timesteps: 5000000
eval_freq: 20000
save_freq: 50000
resume: true
num_envs: 4

# PPO parameters
batch_size: 128
gamma: 0.99
gae_lambda: 0.9
n_steps: 4096
n_epochs: 30
learning_rate: 1e-4

# Vision encoder params
model:
  custom_model: complex_input_network
  conv_filters: [[32, 8, 4], [64, 4, 2], [64, 3, 1]]

# Rendered image to robot
image_width: 128
image_height: 128
vertical_fov: 120

# Depth image upper and lower bounds
depth_low: 0.0
depth_high: 10.0

# Noise parameters
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# Environment params
mode: "headless"
seed: 0
hide_robot: true
clutter: false
build_graph: true
load_texture: true
pybullet_load_texture: false
should_open_all_doors: true
texture_scale: 0.5
trav_map_type: no_obj

# Scene params
scene: igibson
scene_id: Rs_int
not_load_object_categories: [ carpet ]
load_object_categories: [ agent, floor ]

# termination condition
max_step: 500

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# task randomization
randomize_agent_reset: true
randomize_obj_reset: true

# Robot parameters
robot:
  name: Turtlefast
  action_type: discrete
  action_normalize: true
  proprio_obs:
    - trunk_qpos
    - camera_qpos
  reset_joint_pos: null
  base_name: null
  scale: 1.0
  self_collision: true
  rendering_params: null
  controller_config:
    base:
      name: DifferentialDriveController
    camera:
      name: JointController

hydra:
  output_subdir: ${experiment_save_path}/${experiment_name}/hydra
  run:
    dir: ${experiment_save_path}/${experiment_name}/hydra_logging
