# Whatever is in this file will override the experiment
defaults:
  - experiment/search.yaml
  - _self_

# Training params
training_timesteps: 5000000
eval_freq: 20000
save_freq: 50000
resume: true
num_envs: 8

# PPO parameters
batch_size: 128
gamma: 0.99
gae_lambda: 0.9
n_steps: 4096
n_epochs: 30
learning_rate: 1e-4

# Vision encoder params
model:
  custom_model: complex_input_network
  post_fcnet_hiddens: [128, 128, 128]
  conv_filters: [[32, 8, 4], [64, 4, 2], [64, 3, 1]]

# Rendered image to robot
image_width: 128
image_height: 128
vertical_fov: 120

# Depth image upper and lower bounds
depth_low: 0.0
depth_high: 10.0

# Noise parameters
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# Environment params
mode: "gui_interactive"
seed: 0
hide_robot: true
clutter: false
build_graph: true
load_texture: true
pybullet_load_texture: false
should_open_all_doors: true
texture_scale: 0.5
trav_map_type: no_obj

# Scene params
scene: gibson
scene_id: gates_kitchenette
not_load_object_categories: [ carpet ]
load_object_categories: [ agent, floor ]

# termination condition
max_step: 500

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# task randomization
randomize_agent_reset: true
randomize_obj_reset: true

# Robot parameters
# robot:
#   name: Turtlefast
#   action_type: discrete
#   action_normalize: true
#   proprio_obs:
#     - trunk_qpos
#     - camera_qpos
#   reset_joint_pos: null
#   base_name: null
#   scale: 1.0
#   self_collision: true
#   rendering_params: null
#   controller_config:
#     base:
#       name: DifferentialDriveController
#     camera:
#       name: JointController
robot:
  name: Tiago
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - eef_left_pos
    - eef_left_quat
    - eef_right_pos
    - eef_right_quat
    - trunk_qpos
    - arm_left_qpos_sin
    - arm_left_qpos_cos
    - gripper_left_qpos
    - arm_right_qpos_sin
    - arm_right_qpos_cos
    - gripper_right_qpos
    - grasp_left
    - grasp_right
  # reset_joint_pos: null
  # base_name: null
  # scale: 1.0
  # self_collision: false
  # rendering_params: null
  # grasping_mode: physical
  # rigid_trunk: false
  # default_trunk_offset: 0.365
  # default_arm_pose: vertical
  controller_config:
    base:
      name: JointController
    arm_left:
      name: JointController
      motor_type: position
      fixed: true
      default_command: [-1.17, 1.57, 2.74, 1.57, 1.57, -1.41, 0.0]
    gripper_left:
      name: JointController
      motor_type: position
      fixed: true
    arm_right:
      name: JointController
      motor_type: position
      fixed: true
      default_command: [-1.17, 1.57, 2.74, 1.57, 1.57, -1.41, 0.0]
    gripper_right:
      name: JointController
      motor_type: position
      fixed: true
    camera:
      name: JointController
      motor_type: position
      fixed: true
      default_command: [0.0, 0.0]

# sensor spec
output: [rgb, depth, scan, scan_rear]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
# fisheye: false
# image_width: 640
# image_height: 480
# vertical_fov: 45
# depth
# depth_low: 0.8
# depth_high: 3.5
# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
# n_horizontal_rays: 228
# n_vertical_beams: 1

laser_linear_range: 10.0
laser_angular_range: 180.0
min_laser_dist: 0.0
laser_link_name: base_front_laser_link
laser_link_rear_name: base_rear_laser_link

hydra:
  output_subdir: ${experiment_save_path}/${experiment_name}/hydra
  run:
    dir: ${experiment_save_path}/${experiment_name}/hydra_logging
